# 
#  Copyright 2021 DataStax, Inc. 
#  
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  
#      http://www.apache.org/licenses/LICENSE-2.0
#  
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  
# 

default_storage:
  existingStorageClassName: default
persistence: no
enableAntiAffinity: no
enableTls: no 
enableTokenAuth: no
restartOnConfigMapChange:
  enabled: yes
extra:
  function: yes
  burnell: yes
  burnellLogCollector: yes
  pulsarHeartbeat: yes
  pulsarAdminConsole: yes

image:
  broker:
    repository: datastax/pulsar-all
    pullPolicy: IfNotPresent
    tag: latest 
  bookkeeper:
    repository: datastax/pulsar-all
    pullPolicy: IfNotPresent
    tag: latest
  zookeeper:
    repository: datastax/pulsar-all
    pullPolicy: IfNotPresent
    tag: latest
  function:
    repository: datastax/pulsar-all
    pullPolicy: IfNotPresent
    tag: latest
  proxy:
    repository: datastax/pulsar-all
    pullPolicy: IfNotPresent
    tag: latest
  bastion:
    repository: datastax/pulsar-all
    pullPolicy: IfNotPresent
    tag: latest
  burnell:
    repository: datastax/burnell
    pullPolicy: IfNotPresent
    tag: 0.0.1 
  burnellLogCollector:
    repository: datastax/burnell
    pullPolicy: IfNotPresent
    tag: logcollector_0.0.1 
  pulsarHeartbeat:
    repository: datastax/pulsar-monitor
    pullPolicy: IfNotPresent
    tag: 0.0.1 
  pulsarAdminConsole:
    repository: datastax/pulsar-admin-console
    pullPolicy: IfNotPresent
    tag: latest 

cert-manager:
  enabled: no

pulsarHeartbeat:
  config:
    k8sInClusterMonitorEnabled: "false" 

zookeeper:
  replicaCount: 1 
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: "\"-Xms512m -Xmx512m -Djute.maxbuffer=10485760 -XX:+ExitOnOutOfMemoryError\""

bookkeeper:
  replicaCount: 1 
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3
  configData:
    BOOKIE_MEM: "\"-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m -XX:+ExitOnOutOfMemoryError\""

broker:
  component: broker
  replicaCount: 1 
  ledger:
    defaultEnsembleSize: 1 
    defaultAckQuorum: 1 
    defaultWriteQuorum: 1 
  resources:
    requests:
      memory: 600Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: "\"-Xms300m -Xmx300m -XX:MaxDirectMemorySize=300m -XX:+ExitOnOutOfMemoryError\""

autoRecovery:
  resources:
    requests:
      memory: 512Mi
      cpu: 1

function:
  replicaCount: 1 
  functionReplicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3
  configData:
    BOOKIE_MEM: "\"-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m -XX:+ExitOnOutOfMemoryError\""

proxy:
  replicaCount: 1 
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3
  wsResources:
    requests:
      memory: 512Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: "\"-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m\""
  autoPortAssign:
    enablePlainTextWithTLS: yes
  service:
    annotations: {}
    type: NodePort
    autoPortAssign:
      enabled: yes

grafanaDashboards:
  enabled: yes
  namespaceOverride: ''

pulsarAdminConsole:
  replicaCount: 1
  ingress:
    enabled: no

kube-prometheus-stack:
  enabled: yes
  namespaceOverride: ''
  prometheusOperator:
    enabled: true
  grafana:
    enabled: true
    adminPassword: e9JYtk83*4#PM8
    namespaceOverride: ''
    ingress:
      enabled: no
    testFramework:
      enabled: false
  prometheus:
    service:
      type: NodePort
    prometheusSpec:
      storageSpec: null

  
